steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=gcp/Dockerfile.ragtruth-cpu
      - --build-arg=SOURCE_COMMIT=${_SOURCE_COMMIT}
      - --build-arg=RUNNER_SOURCE_COMMIT=${_RUNNER_SOURCE_COMMIT}
      - --tag=${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
